on:
  pull_request:
    branches: main
name: Validate pull request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - name: Setup environment
      run: npm ci
    - name: Test files in pull request
    - run: npm test
    - name: Build new index file
      run: npm run build
    - name: Test new index file
      run: npm test
